### ISSUE TITLE
Render of forbidden.pt on login failure is not working

### ISSUE THREAD

**Issue by Kruecke** [bird-house/pyramid-phoenix#26]
In `phoenix/views/account.py` the lines 142 to 144 are resulting in TypeErrors.

Easy test: `http://localhost:8081/account/openid?id=example.com%2Ftest`

There is a problem generating the logging string:
```
2015-06-01 15:07:28,414 ERROR [phoenix.views][MainThread] unknown failure
Traceback (most recent call last):
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/fklemme/Repositories/pyramid-phoenix/phoenix/views/account.py", line 142, in openid
    self.session.flash('Sorry, login failed: %s', queue='danger' % (result.error.message))
TypeError: not all arguments converted during string formatting
```

If you comment out lines 142 and 143, there is still a problem rendering forbidden.pt:
```
2015-06-01 15:10:12,942 ERROR [phoenix.views][MainThread] unknown failure
Traceback (most recent call last):
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/fklemme/Repositories/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/fklemme/Repositories/pyramid-phoenix/phoenix/views/account.py", line 144, in openid
    response.text = render('phoenix:templates/account/forbidden.pt', request=self.request)
TypeError: render() takes at least 2 arguments (2 given)
```
The message is a little bit confusing. I assume he's missing a dictionary as the second positional argument.

**Comment by Kruecke** [comment]
I fixed the TypeErrors with 41fffad2c6b17462f84f811713a69482ec3e35ca but there is still a problem with the render function. It looks like the `view` object is missing...

```
AttributeError: 'NoneType' object has no attribute 'title'

 - Expression: " 
        <div class="page-header" tal:condition="view.description | None">
          <h1>${view.title} <small>${view.description}</small></h1>
        </div>
        "
 - Filename:   ... ies/pyramid-phoenix/phoenix/templates/layouts/default.pt
 - Location:   (line 82: col 12)
 - Source:     ... 
                   ^
 - Arguments:  repeat: {...} (0)
               renderer_name: phoenix:templates/account/forbidden.pt
               renderer_info: <RendererHelper - at 0x2aafa3170fd0>
               message: 
               panel: <instancemethod render_panel at 0x2aafa3169f00>
               layout: <PageLayout - at 0x2aafa3170a10>
               req: <Request - at 0x2aafa0d86fd0>
               request: <Request - at 0x2aafa0d86fd0>
               main_template: <PyramidPageTemplateFile - at 0x2aafa317b410>
               context: <instance - at 0x2aafa316e098>
               message_type: alert-info
               view: <NoneType - at 0x2aaf99c69970>
```

**Comment by Kruecke** [comment]
This effect is also described here: http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/templates.html#system-values-used-during-rendering

**Comment by Kruecke** [comment]
This error was actually caused by some (supposed to be) dead code within a html comment. (Maybe the template compiler isn't working properly here.)

Fixed it with some escaping within the comment.
