### ISSUE TITLE
OpenID login failure on clean installation

### ISSUE THREAD

**Issue by fklemme** [bird-house/pyramid-phoenix#30]
Just caught this one. Quick guess: I haven't added any admin e-mails to custom.cfg. (Haven't touched anything at all, just cloned and ran phoenix.)

```
2015-06-19 16:18:18,349 INFO  [140319115413200][MainThread] authomatic: OpenID: Starting OpenID authentication procedure.
2015-06-19 16:18:18,418 DEBUG [140319115413200][MainThread] authomatic: OpenID: SessionOpenIDStore: Association not found.
2015-06-19 16:18:18,851 DEBUG [140319115413200][MainThread] authomatic: OpenID: SessionOpenIDStore: Storing association to session.
2015-06-19 16:18:18,852 INFO  [140319115413200][MainThread] authomatic: OpenID: Service discovery for identifier http://florianklemme.de successful.
2015-06-19 16:18:18,853 INFO  [140319115413200][MainThread] authomatic: OpenID: Writing an auto-submit HTML form to the response.
2015-06-19 16:18:21,882 INFO  [140319115123728][MainThread] authomatic: OpenID: Continuing OpenID authentication procedure after redirect.
2015-06-19 16:18:21,883 DEBUG [140319115123728][MainThread] authomatic: OpenID: SessionOpenIDStore: Association found.
2015-06-19 16:18:21,887 INFO  [140319115123728][MainThread] authomatic: OpenID: Authentication successful.
2015-06-19 16:18:21,887 INFO  [140319115123728][MainThread] authomatic: OpenID: Got AX data.
2015-06-19 16:18:21,887 INFO  [140319115123728][MainThread] authomatic: OpenID: Got SREG data.
2015-06-19 16:18:21,887 INFO  [140319115123728][MainThread] authomatic: OpenID: Procedure finished.
2015-06-19 16:18:21,887 INFO  [phoenix.views.account][MainThread] openid login successful for user mail@florianklemme.de
2015-06-19 16:18:21,887 INFO  [phoenix.views.account][MainThread] openid login successful for user mail@florianklemme.de
2015-06-19 16:18:21,888 WARNI [phoenix.views.account][MainThread] openid login: new user mail@florianklemme.de
2015-06-19 16:18:21,888 WARNI [phoenix.views.account][MainThread] openid login: new user mail@florianklemme.de
2015-06-19 16:18:22,445 ERROR [phoenix.views][MainThread] unknown failure
Traceback (most recent call last):
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/kruecke/pyramid-phoenix/phoenix/views/account.py", line 166, in openid
    self.login_success(email=result.user.email, openid=result.user.id, name=result.user.name)
  File "/home/kruecke/pyramid-phoenix/phoenix/views/account.py", line 98, in login_success
    self.send_notification(email, subject, message)
  File "/home/kruecke/pyramid-phoenix/phoenix/views/account.py", line 87, in send_notification
    mailer.send_immediately(message, fail_silently=True)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid_mailer-0.14.1-py2.7.egg/pyramid_mailer/mailer.py", line 275, in send_immediately
    return self.smtp_mailer.send(*self._message_args(message))
  File "/home/kruecke/pyramid-phoenix/eggs/repoze.sendmail-4.2-py2.7.egg/repoze/sendmail/mailer.py", line 100, in send
    connection.sendmail(fromaddr, toaddrs, message)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/smtplib.py", line 742, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'': (501, '5.1.3 Bad recipient address syntax')}
2015-06-19 16:18:22,445 ERROR [phoenix.views][MainThread] unknown failure
Traceback (most recent call last):
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/kruecke/pyramid-phoenix/phoenix/views/account.py", line 166, in openid
    self.login_success(email=result.user.email, openid=result.user.id, name=result.user.name)
  File "/home/kruecke/pyramid-phoenix/phoenix/views/account.py", line 98, in login_success
    self.send_notification(email, subject, message)
  File "/home/kruecke/pyramid-phoenix/phoenix/views/account.py", line 87, in send_notification
    mailer.send_immediately(message, fail_silently=True)
  File "/home/kruecke/pyramid-phoenix/eggs/pyramid_mailer-0.14.1-py2.7.egg/pyramid_mailer/mailer.py", line 275, in send_immediately
    return self.smtp_mailer.send(*self._message_args(message))
  File "/home/kruecke/pyramid-phoenix/eggs/repoze.sendmail-4.2-py2.7.egg/repoze/sendmail/mailer.py", line 100, in send
    connection.sendmail(fromaddr, toaddrs, message)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/smtplib.py", line 742, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'': (501, '5.1.3 Bad recipient address syntax')}
```

**Comment by cehbrecht** [comment]
which openid provider are you using? Currently esgf openids are not available ... i might have broken the "normal" openid login.

**Comment by Kruecke** [comment]
I'm using https://openid.stackexchange.com/. You can get an account very easily and for free there, if you want to test it.

(I did use OpenID delegation on my own domain, florianklemme.de, but this should not affect anything, I guess.)

**Comment by cehbrecht** [comment]
i've cleaned up code for openid. The stockexchange sometimes work ... sometimes i get a `Bad signature` error ... don't know.

the account module is now using `login_id` instead of `userid`.

**Comment by cehbrecht** [comment]
the general openid login is disabled.
