### ISSUE TITLE
can not register zoo wps

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/pyramid-phoenix#72]
try to register: http://zoo-project.org/cgi-bin/zoo_loader3.cgi

csw harvest fails:

    2016-06-02 17:18:35,353 ERROR [phoenix.services.views.registerservice][DummyThread-72] could not register service.
    Traceback (most recent call last):
      File "/home/Shared/pingu/sandbox/birdhouse/pyramid-phoenix/phoenix/services/views/registerservice.py", line 56, in process_form
    self.request.catalog.harvest(**appstruct)
     File "/home/Shared/pingu/sandbox/birdhouse/pyramid-phoenix/phoenix/catalog.py", line 111, in harvest
    self.csw.harvest(source=url, resourcetype=service_type)
     File "/home/pingu/.conda/envs/birdhouse/lib/python2.7/site-packages/owslib/csw.py", line 488, in harvest
    self._invoke()
     File "/home/pingu/.conda/envs/birdhouse/lib/python2.7/site-packages/owslib/csw.py", line 688, in _invoke
    raise ows.ExceptionReport(self._exml, self.owscommon.namespace)
    ExceptionReport: "Harvest failed: record parsing failed: '{http://www.w3.org/1999/xlink}href'"

**Comment by cehbrecht** [comment]
fixed in owslib: parsing error of process ows:metadata ... href was missing (optional)
