### ISSUE TITLE
LDAP failed to connect

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/pyramid-phoenix#95]
@Kruecke 

LDAP failed to connect, after reinstall with new (bird separated) environment:

2016-07-13 19:03:44,225 DEBUG [pyramid_ldap][DummyThread-13] searching for ('ou=lsce,dc=extra,dc=fr', 2, '(uid=nhempel)')
2016-07-13 19:03:44,226 ERROR [twitcher.tweens][DummyThread-13] unknown error
Traceback (most recent call last):
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid_twitcher-0.1.7-py2.7.egg/twitcher/tweens.py", line 27, in ows_security_tween
    return handler(request)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/router.py", line 158, in handle_request
    view_name
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid-1.7-py2.7.egg/pyramid/viewderivers.py", line 123, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/homel/birdhouse/pyramid-phoenix/phoenix/account/views.py", line 246, in login
    return self.process_form(form, protocol)
  File "/homel/birdhouse/pyramid-phoenix/phoenix/account/views.py", line 157, in process_form
    return self.ldap_login()
  File "/homel/birdhouse/pyramid-phoenix/phoenix/account/views.py", line 342, in ldap_login
    auth = connector.authenticate(username, password)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid_ldap-0.1-py2.7.egg/pyramid_ldap/__init__.py", line 117, in authenticate
    result = search.execute(conn, login=login, password=password)
  File "/homel/birdhouse/pyramid-phoenix/eggs/pyramid_ldap-0.1-py2.7.egg/pyramid_ldap/__init__.py", line 79, in execute
    result = conn.search_s(*cache_key)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 552, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 873, in search_ext_s
    return self._apply_method_s(SimpleLDAPObject.search_ext_s,*args,**kwargs)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 815, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 546, in search_ext_s
    return self.result(msgid,all=1,timeout=timeout)[1]
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 458, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 462, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/home/estimr2/birdhouse/.conda/envs/pyramid-phoenix/lib/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
NO_SUCH_OBJECT: {'desc': 'No such object'}
2016-07-13 19:03:44,230 DEBUG [beaker.container][DummyThread-13] data file /homel/birdhouse/birdhouse/var/cache/phoenix/sessions/data/container_file/9/9c/9c7afda96ce243b08f3d3da338379f29.cache
(END)

**Comment by nilshempelmann** [comment]
had simply been a wrong entry in the GUI ...
